// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyLibrary.Models;

namespace ToyLibrary.Migrations
{
    [DbContext(typeof(ToyLibraryContext))]
    [Migration("20220907032447_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ToyLibrary.Models.Toy", b =>
                {
                    b.Property<int>("ToyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4");

                    b.Property<int>("UserAgeMaximum")
                        .HasColumnType("int");

                    b.Property<int>("UserAgeMinimum")
                        .HasColumnType("int");

                    b.HasKey("ToyId");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            ToyId = 1,
                            Description = "Shape-sorting cube with 6 rubbery shapes tethered to its corners",
                            Name = "Oombee Cube Sorter",
                            UserAgeMaximum = 2,
                            UserAgeMinimum = 1
                        },
                        new
                        {
                            ToyId = 2,
                            Description = "Colorful transparent pipes that easily stick to the bathtub walls to build all kinds of fascinating waterfall chains.",
                            Name = "Boon Pipes Building Bath Toy",
                            UserAgeMaximum = 3,
                            UserAgeMinimum = 1
                        },
                        new
                        {
                            ToyId = 3,
                            Description = "3D magnetic building tiles in bright colors and classic geometric shapes.",
                            Name = "Magna Tiles",
                            UserAgeMaximum = 17,
                            UserAgeMinimum = 1
                        },
                        new
                        {
                            ToyId = 4,
                            Description = "60 Snap-Together parts consisting of electrical components that can be used to make circuits and learn about electricity.",
                            Name = "Elenco Snap Circuits Classic",
                            UserAgeMaximum = 17,
                            UserAgeMinimum = 8
                        },
                        new
                        {
                            ToyId = 5,
                            Description = "Paddleboard designed for kids ages 5 and up or up to 130 lb. Great stability and tracking in both surf and flat water. Constructed of UV-protected High-Density Polyethylene",
                            Name = "Lifetime Hooligan Youth Paddleboard",
                            UserAgeMaximum = 17,
                            UserAgeMinimum = 5
                        },
                        new
                        {
                            ToyId = 6,
                            Description = "A board game that incorporates a smartphone app and virtual reality. Feels like a modern update to Clue for the tech-savvy teen. Players are presented with an unsolved murder or heist, and they determine who committed the crime, which weapons were used, and why.",
                            Name = "Chronicles of Crime",
                            UserAgeMaximum = 17,
                            UserAgeMinimum = 16
                        },
                        new
                        {
                            ToyId = 7,
                            Description = "Soft and cuddly 12-inch gender neutral baby doll. An ideal first doll that will encourage little ones to role play, nurture and care. ",
                            Name = "Wee Baby Stella",
                            UserAgeMaximum = 4,
                            UserAgeMinimum = 1
                        },
                        new
                        {
                            ToyId = 8,
                            Description = "Wood and plastic Ikea train train set. Children can load and unload the cars as they like since the upper parts are detachable.",
                            Name = "Lillabo 3 Piece Train Set",
                            UserAgeMaximum = 5,
                            UserAgeMinimum = 3
                        },
                        new
                        {
                            ToyId = 9,
                            Description = "Players hike along the trail, collecting rocks, acorns and leaves; taking pictures; and encountering wildlife to gain bonuses. Game explores national parks across the US.",
                            Name = "Trails: A Parks Game",
                            UserAgeMaximum = 17,
                            UserAgeMinimum = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
